import type { CSSProperties } from "react";

type FlexboxStyle = Partial<
  Pick<
    CSSProperties,
    "flexDirection" | "justifyContent" | "alignItems" | "gap" | "flexWrap"
  >
>;

export type Difficulty = "Latwy" | "Sredni" | "Trudny";

export type Level = {
  id: number;
  title: string;
  difficulty: Difficulty;
  task: string;
  hint: string;
  dotQty: number;
  initialStyle: FlexboxStyle;
  goal: FlexboxStyle;
};

export const levels: Level[] = [
  {
    id: 1,
    title: "Vertical Stack",
    difficulty: "Latwy",
    task: "Ustaw kropki jedna pod druga.",
    hint: "Zmien os glowna na pionowa.",
    dotQty: 4,
    initialStyle: { flexDirection: "row", justifyContent: "flex-start", alignItems: "center" },
    goal: { flexDirection: "column" },
  },
  {
    id: 2,
    title: "Center Stage",
    difficulty: "Latwy",
    task: "Wycentruj kropki w poziomie.",
    hint: "To wyrownanie po osi glownej.",
    dotQty: 4,
    initialStyle: { flexDirection: "row", justifyContent: "flex-start" },
    goal: { justifyContent: "center" },
  },
  {
    id: 3,
    title: "Perfect Space",
    difficulty: "Latwy",
    task: "Rozloz kropki rownomiernie po szerokosci.",
    hint: "Szukaj opcji z rownymi odstepami miedzy elementami.",
    dotQty: 4,
    initialStyle: { flexDirection: "row", justifyContent: "flex-start" },
    goal: { justifyContent: "space-between" },
  },
  {
    id: 4,
    title: "Drop Zone",
    difficulty: "Latwy",
    task: "Przesun wszystkie kropki na dol kontenera.",
    hint: "To wyrownanie po osi poprzecznej.",
    dotQty: 3,
    initialStyle: { flexDirection: "row", alignItems: "flex-start" },
    goal: { alignItems: "flex-end" },
  },
  {
    id: 5,
    title: "Reverse Flow",
    difficulty: "Latwy",
    task: "Odwroc kolejnosc kropek w poziomie.",
    hint: "Uzyj odwroconego wariantu dla row.",
    dotQty: 5,
    initialStyle: { flexDirection: "row" },
    goal: { flexDirection: "row-reverse" },
  },
  {
    id: 6,
    title: "Top Line",
    difficulty: "Latwy",
    task: "Ustaw kropki na gorze kontenera.",
    hint: "Wplywa na os poprzeczna.",
    dotQty: 4,
    initialStyle: { alignItems: "center" },
    goal: { alignItems: "flex-start" },
  },
  {
    id: 7,
    title: "Left Start",
    difficulty: "Latwy",
    task: "Ustaw kropki na poczatku osi glownej.",
    hint: "Wybierz podstawowa wartosc wyrownania poziomego.",
    dotQty: 4,
    initialStyle: { justifyContent: "center" },
    goal: { justifyContent: "flex-start" },
  },
  {
    id: 8,
    title: "Vertical Reverse",
    difficulty: "Latwy",
    task: "Odwroc kolejnosc kropek pionowo.",
    hint: "To pionowy odpowiednik row-reverse.",
    dotQty: 4,
    initialStyle: { flexDirection: "column" },
    goal: { flexDirection: "column-reverse" },
  },
  {
    id: 9,
    title: "Soft Gap",
    difficulty: "Latwy",
    task: "Dodaj mniejszy odstep miedzy kropkami.",
    hint: "Skorzystaj z gap w pikselach.",
    dotQty: 4,
    initialStyle: { gap: "0px" },
    goal: { gap: "8px" },
  },
  {
    id: 10,
    title: "Tight Center",
    difficulty: "Latwy",
    task: "Wycentruj kropki pionowo.",
    hint: "To align-items center.",
    dotQty: 5,
    initialStyle: { alignItems: "flex-start" },
    goal: { alignItems: "center" },
  },
  {
    id: 11,
    title: "Center Axis",
    difficulty: "Sredni",
    task: "Wycentruj kropki po osi glownej i ustaw je na gorze.",
    hint: "Potrzebne beda dwie wlasciwosci.",
    dotQty: 5,
    initialStyle: { justifyContent: "flex-start", alignItems: "center" },
    goal: { justifyContent: "center", alignItems: "flex-start" },
  },
  {
    id: 12,
    title: "Wide Split",
    difficulty: "Sredni",
    task: "Rozsun kropki i ustaw je na dole.",
    hint: "Polacz justify-content i align-items.",
    dotQty: 5,
    initialStyle: { justifyContent: "center", alignItems: "center" },
    goal: { justifyContent: "space-between", alignItems: "flex-end" },
  },
  {
    id: 13,
    title: "Column Focus",
    difficulty: "Sredni",
    task: "Ustaw pionowy uklad i wycentruj elementy po osi poprzecznej.",
    hint: "Najpierw os, potem wyrownanie.",
    dotQty: 4,
    initialStyle: { flexDirection: "row", alignItems: "flex-start" },
    goal: { flexDirection: "column", alignItems: "center" },
  },
  {
    id: 14,
    title: "Reverse Center",
    difficulty: "Sredni",
    task: "Odwroc rzad i wycentruj kropki.",
    hint: "Zmiana kierunku + pozycjonowanie.",
    dotQty: 5,
    initialStyle: { flexDirection: "row", justifyContent: "flex-start" },
    goal: { flexDirection: "row-reverse", justifyContent: "center" },
  },
  {
    id: 15,
    title: "Balanced Gap",
    difficulty: "Sredni",
    task: "Dodaj wyrazny odstep i ustaw kropki centralnie.",
    hint: "gap + justify-content.",
    dotQty: 4,
    initialStyle: { gap: "0px", justifyContent: "flex-start" },
    goal: { gap: "20px", justifyContent: "center" },
  },
  {
    id: 16,
    title: "Column Bottom",
    difficulty: "Sredni",
    task: "Ustaw pionowy uklad i przenies kropki na dol.",
    hint: "Po zmianie osi osie rowniez zmieniaja role.",
    dotQty: 4,
    initialStyle: { flexDirection: "row", justifyContent: "flex-start" },
    goal: { flexDirection: "column", justifyContent: "flex-end" },
  },
  {
    id: 17,
    title: "Center Duo",
    difficulty: "Sredni",
    task: "Ustaw kropki dokladnie na srodku planszy.",
    hint: "Poziom i pion jednoczesnie.",
    dotQty: 5,
    initialStyle: { justifyContent: "space-between", alignItems: "flex-start" },
    goal: { justifyContent: "center", alignItems: "center" },
  },
  {
    id: 18,
    title: "Reverse Tower",
    difficulty: "Sredni",
    task: "Ustaw odwrocona kolumne i wyrownaj do konca osi poprzecznej.",
    hint: "column-reverse i align-items.",
    dotQty: 4,
    initialStyle: { flexDirection: "row", alignItems: "center" },
    goal: { flexDirection: "column-reverse", alignItems: "flex-end" },
  },
  {
    id: 19,
    title: "Even Orbit",
    difficulty: "Sredni",
    task: "Rozstaw kropki z jednakowymi marginesami wokol.",
    hint: "Uzyj wariantu space-around.",
    dotQty: 5,
    initialStyle: { justifyContent: "flex-start" },
    goal: { justifyContent: "space-around" },
  },
  {
    id: 20,
    title: "Wrap Start",
    difficulty: "Sredni",
    task: "Wlacz zawijanie elementow w wielu wierszach.",
    hint: "To osobna wlasciwosc niz direction.",
    dotQty: 8,
    initialStyle: { flexWrap: "nowrap" },
    goal: { flexWrap: "wrap" },
  },
  {
    id: 21,
    title: "Chaos Control",
    difficulty: "Trudny",
    task: "Wlacz zawijanie i ustaw kropki na srodku osi glownej.",
    hint: "Potrzebujesz flex-wrap i justify-content.",
    dotQty: 8,
    initialStyle: { flexWrap: "nowrap", justifyContent: "flex-start" },
    goal: { flexWrap: "wrap", justifyContent: "center" },
  },
  {
    id: 22,
    title: "Reverse Grid",
    difficulty: "Trudny",
    task: "Odwroc rzad, wlacz wrap i dodaj odstep.",
    hint: "Trzy wlasciwosci naraz.",
    dotQty: 9,
    initialStyle: { flexDirection: "row", flexWrap: "nowrap", gap: "0px" },
    goal: { flexDirection: "row-reverse", flexWrap: "wrap", gap: "8px" },
  },
  {
    id: 23,
    title: "Column Matrix",
    difficulty: "Trudny",
    task: "Ustaw pionowy uklad, zawijanie i wyrownanie do konca osi glownej.",
    hint: "W tym poziomie os glowna jest pionowa.",
    dotQty: 9,
    initialStyle: { flexDirection: "row", flexWrap: "nowrap", justifyContent: "flex-start" },
    goal: { flexDirection: "column", flexWrap: "wrap", justifyContent: "flex-end" },
  },
  {
    id: 24,
    title: "Precision Mix",
    difficulty: "Trudny",
    task: "Rozstaw rowno kropki i ustaw je na dole z duzym gap.",
    hint: "Cel wymaga trzech ustawien.",
    dotQty: 8,
    initialStyle: { justifyContent: "flex-start", alignItems: "flex-start", gap: "0px" },
    goal: { justifyContent: "space-evenly", alignItems: "flex-end", gap: "20px" },
  },
  {
    id: 25,
    title: "Grand Finale",
    difficulty: "Trudny",
    task: "Final: odwrocona kolumna, wrap, idealny srodek i odstepy.",
    hint: "Polacz wszystkie kluczowe elementy flexbox.",
    dotQty: 10,
    initialStyle: {
      flexDirection: "row",
      flexWrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "flex-start",
      gap: "0px",
    },
    goal: {
      flexDirection: "column-reverse",
      flexWrap: "wrap",
      justifyContent: "center",
      alignItems: "center",
      gap: "8px",
    },
  },
];
